version: '3.4'

services:
  wdta2api:
    image: ${DOCKER_REGISTRY-}wdta2api
    build:
      context: .
      dockerfile: WdtA2Api/Dockerfile

  wdtconsumer:
    image: ${DOCKER_REGISTRY-}wdtconsumer
    build:
      context: .
      dockerfile: WdtConsumer/Dockerfile

